### PR TITLE
fix: Master battery set button does not work on honeycomb volant

### PR DESCRIPTION
**Pull request by NewoPL**
Some guess what may be wrong with honeycomb volant. please verify if it works

### CODE REVIEW

**Review by magraina — APPROVED** [review]

**Comment by magraina** [comment]
@NewoPL Doesn't work fully yet.
The event "TOGGLE MASTER BATTERY" works just fine. Switches on and off the Bus Connection
ALT+B works just the same.

The honeycomb uses "SET MASTER BATTERY" by default. But It cannot use a toggle event.
The event for "SET MASTER BATTERY", "MASTER BATTERY ON", "MASTER BATTERY OFF" and "SET BATTERY 1" does not switch the bus connection.
It only switches the battery itself on:
image
or off:
image

So you're unable to switch the battery with the honeycomb, if you are using the in-game controls setup

**Comment by magraina** [comment]
Updated the screenshot, cause it was the wrong one.
If you are press a switch on the honeycomb the input will stay active like if you're holding a key on the keyboard and vice versa.
That's the reason why you could not use toggle.

**Comment by magraina** [comment]
I may have something wrong on my setup. Let me check double check that

**Comment by magraina** [comment]
Okay I checked it again. For whatever reason I hadn't the right changes from this pull request.

With this Pull Request the "SET MASTER BATTERY" works!
But the  "MASTER BATTERY ON", "MASTER BATTERY OFF" and "SET BATTERY 1" behaves still like described before.

**Comment by NewoPL** [comment]
thanks for verification magraina,
Main battery should stay on all the time, it is correct
the set master battery and toggle master battery should connect and
disconnect battery  bus and power distro bus
if i bing set master battery to a key on my keyboard it functions correctly
it is exactly as you write if i press the bound key it connects the switch
if i release the key on the keyboard the switch is turned off
what is diffrent on honeycomb that this binding does not function ?
does it use something else thatn set Master battery ?

**Comment by NewoPL** [comment]
ah ok then.
Are those other events used by honeycomb as well ?

**Comment by magraina** [comment]
No the honeycomb does not use them. So at least the Honeycomb will work with it.
But the stock implementation does use them.
"SET BATTERY 1" should behave like "SET MASTER BATTERY"
And "MASTER BATTERY ON" and "MASTER BATTERY OFF" should just do on and off.
Depends on you if you want to implement them too (doesn't have to be right now).

**Pull request merged**
