### PR TITLE
a couple of small various fixes left after last pull.

### PR DESCRIPTION
**Pull request by NewoPL**
a couple of small various fixes left after last pull.

### CODE REVIEW

**Review by magraina — APPROVED** [review]

**Comment by magraina** [comment]
I'm curious to know! How have you found this option in the gltf file for the Standby Alternator Light?

**Comment by NewoPL** [comment]
oh.. you can import a gftl model in Blender and there you basically can do
everything with it.
it is how they develop a320 neo mod.

**Comment by magraina** [comment]
Thanks! I haven't used blender so far
Maybe there are also a possibility to change the min and max position of the Standby Torque Indicator

**Comment by NewoPL** [comment]
what is wrong with standby torque indicator ?
i was just observing its indications and i havent' noticed anything strange

**Comment by magraina** [comment]
It's the wrong picture.
I faked it, cause the right picture has a different scale.
So if I'm using the right picture it will not show the correct value cause the position of maximum is different.
I can share a picture later to make it clear.

**Comment by NewoPL** [comment]
Thanks for the explanation. I looked at your modified texture,
However, I can see the scale is exactly the same, but you changed the range
of the green area.
So the needle should point exactly to the same value for original and
modified texture.
The only thing is what value should be red, do you know what it is on the
real aircraft ?
Do you want to change the scale above the 2500 foot pounds ?

**Comment by NewoPL** [comment]
I browsed through the internet and found a picture of the real thing :)
[image: image.png]
I think you nailed it right. It is exactly as on the real plane. And your
solution is really clean.
I am not sure what would you like to change
thanks
newo

**Comment by NewoPL** [comment]
Ok maybe you mean that the hand does not traverse fully to the end of the
scale ? 2500 ? it stops around 2400 .
Is that right ?

**Comment by NewoPL** [comment]
I think I fixed it. I am sorry, without thinking i put it on the same
branch so landed in the same pull request.

**Comment by magraina** [comment]
@NewoPL 
That's what Asobo has provided
Its the Indicator for the Standard C208
image

This is how it should look like in the EX Version:
image

And that's how I fake it cause I don't know how to change the position of the needle: 
image

**Comment by magraina** [comment]
I created a branch [TorqueIndicator](https://github.com/SheepCreativeSoftware/msfs2020-C208-Improvment-Mod/tree/TorqueIndicator) with the right picture in it
If you have an idea how to solve that?

**Comment by NewoPL** [comment]
Hi, I submitted a new pull request for the solution.

**Comment by magraina** [comment]
I have seen it!
Hadn't thought that would be so easy to fix!
Thank you very much!😊

**Comment by NewoPL** [comment]
Yes the fix was easy, but I had to change the texture as well to fine tune
the alignment with needle movement, that took most of the time.
Thanks !

**Comment by magraina** [comment]
Oh, I thought it's the same.
Looks now mich better then my fake one.

**Pull request merged**
