### PR TITLE
Electrical system bug fixes and modifications

### PR DESCRIPTION
**Pull request by NewoPL**
1. Changed the electric bus configuration to comply with POH. Cabin light connected directly to battery bus. Battery switch disconnects battery bus instead of the battery itself, Needed to connect cabin lights directly to hot battery bus and make it possible to enable them independently of the position of the master battery switch. It required custom Power Switch implementation to make it work properly, plus changes in the sound configuration file plus, fixes for default FLT configurations
2. fix for a problem with External Power switch. it did not reconnect starter to battery when external power was disconnected
3. Generator switch has been fixed. Right now it is possible to trip the main generator. 
4. Generator characteristics have been modified: Workaround for now to simulate lack of power during the startup.
5. Fixed the panel emblem light knob
6. Cabin Lights fix - the switch right now properly enables or disables cabin aft lights. POH is saying the same switch should also enable front lights. That is left for improvement later.
7. I tried to increase the brightness of the stby alternator light. It looks like the texture needs some improvement too.
8. Fixed configuration of PFD and MFD - they properly initialize right now. Avionics 1 switch enables only PFD 1.

### CODE REVIEW

**Comment by magraina** [comment]
I will need to check that. 
It will not be fully compatible with my latest changes which change things like this already but in a complete different way.

Also I don't understand some changes yet, cause I don't see a change to original behavior or i don't know what this changes are supposed to do.

**Comment by NewoPL** [comment]
Thanks magraina, yes I missed that that there are additional changes on beta branch. There are already fixes for cabin lights problem, I did the merge. there were a couple of small conflicts easy to resolve.

**Comment by magraina** [comment]
@NewoPL okay thank you for contribute!
I will review that in the next days.

**Review by magraina — APPROVED** [review]

**Review by magraina — DISMISSED** [review]

**Review by magraina — COMMENTED** [review]
**panel.xml**
What about the reversionary mode? 
Why is the MFD commented out?

**Comment by magraina** [comment]
@NewoPL 
Almost done, but two questions?
**On panel.xml**
What about the reversionary mode? 
Why is the MFD commented out?

**Comment by NewoPL** [comment]
You are right, those are needed for default garmin avionics. 
I will fix that yet.

**Review by magraina — APPROVED** [review]

**Pull request merged**
