### PR TITLE
Next release fixes & enhancments

### LINKED ISSUE #115: Missing install zip for v2201.3 release

### LINKED ISSUE #117: Cockpit light knob controls inverted
User feedback from flightsim.to
> Very nice MOD ! Gave the Caravan a new life ! Thank you very much for this ! I wrote a PM for you regarding something I found. Since you changed the cockpit light knobs names (CB/Pedestal/OVH to Left Flood) and (Left Flood to Center Flood), the knob controls are inverted (Left knob controlling the Center light and Center Knob controlling the left light). As for the rest, it works perfectly. Plane feels smoother and better to fly ! Many thanks !

### PR DESCRIPTION
**Pull request by NewoPL**
**2203.1.0**
- fix #115: added support for MASTER_BATTERY_ON and MASTER_BATTERY_OFF events
- fix: XML standard adherence
- fix: stby torque indicator is not lit
- fix: cockpit flood lights current consumption changes with light intensity
- fix: avionics, stby instruments and other panel lights current consumption does not change with light intensity
- fix #117: various improvment to internal lights setting, cabin ambient light improved. Right now cabin lights dim when battery is almost discharged
- add: Internal light initialisation + cleanup
- fix: tooltips does not work for modified controls (battery, generator and alternator switches)
- fix: the order of CAS messages on FD
- cleanup: move new mod templates to dedicated files. Remove garbage files.
- fix: migrate to new autostart / autostop procedure handling
- Improvment: starter-motor position is sprint loaded and mechanically connected with ignition switch,
- fix: main generatior is not connected to the system until start switch returns to off position.
- fix: ignition remains on until starter switch returns to off position or when the ignition switch is in norm position
- fix: initialisation of ignition switch does not work. setup default value for Norm for all flight phases.
- fix: do not enter starter mode for NG>46%.
- fix: battery current indication changes to red when battery is discharged,
- fix: fuel gauge correction
- fix: realignement of gauges to prepare space for anti ice system implementation.
- improvment: Added anti Ice fluid application when anti ice system is turned on. added missing A-ICE CAS messages.
- improvment: the starter current load depends partly on the external temperature.
- improvment: electric system changes description
- improvment: Experimental Anti Ice system implemtnation.
- improvment: added stall sensor heater switch (inop for now)
- improvment: added windshield deice switch logic
- Added: anti-ice system description added to readme file
- fix: added additional chart and reference to readme file
- improvment: added deice pump elecric circuit logic
- improvment: added stall heater implemntation
- fix: added stall heater description and some final tweaks of the system
- improvment: added lgoic for propeller speed governor test switch
- fix: sound is doubled when goveronor test button is released. Min Goverend RPMS set to 1500 RPM.
- fix: get rid of template related problems, fix deice tooltips
- improvment: Added logic for CAS announciation test switch
- fix: tone warning does not work
- fix: Cold and Dark configuration. Initialisation of fuelshutoff valve. It is possible now to set the valve to open state and condition leaver to cutoff state.
- fix: merge with SimUpdate8 model

### CODE REVIEW

**Comment by NewoPL** [comment]
It is yet unclear to me what is the effect when start switch is moved when engine is running.  Especially what is the effect on generator connection or ignition system

**Comment by magraina** [comment]
Okay so you couldn't test it yet?
I maybe can test your changes in the next days

**Comment by NewoPL** [comment]
i am just not sure what the correct behaviour of the systems should be when you switch start switch during the flight. I dont fully understand when the generator off notification should pop up.

**Comment by magraina** [comment]
I do yet not really understand what this change does. I thought the stock behavior was not that bad compared to the original.
If starter switch is set inflight it should do nothing at all, cause Motor-Generator should act like generator.

**Comment by magraina** [comment]
What I have read in the POH the generator should automatically get active even when starter switch is set on. If engine runs at or above 46% Ng
So CAS Annunciation for starter and Ignition should disappear when this happens (if there is no failure)
That could also be seen in the video I posted at my latest changes on the annunciations.

A spring loaded switch will maybe have a problem with controlers (like honeycomb), cause it springs back even when the switch is still pressed.
So it should also act like a normal not spring loaded switch if it is used with key bindings.

**Comment by NewoPL** [comment]
I refer to this section, which says the generatior is connected when starter switch returns to off position: not when the engine is running above 46 % Ng.
image

**Comment by NewoPL** [comment]
Ignition is terminated when start switch goes to off position as well.
image
It is seen on the movie.

**Comment by NewoPL** [comment]
I was trying to figure ot what happens when start switch is switched on when the engine is running. Does it mean the ignition is turned on and the gereator is disconnected again ?

**Comment by magraina** [comment]
So again what I said in the latest pull request
According to POH:
The GCU provides for automatic starter cutoff when engine RPM is above 46%.
Below 46%, the starter-generator functions as a starter, and above
46%, the starter-generator functions as a generator

GENERATOR OFF (AMBER) - Indicates that the generator is not
connected to the electrical bus "with engine running".
STARTER ON (AMBER) - Indicates the starter-generator is
operating in starter mode.

After the engine has stabilized at idle, the amber STARTER ON annunciator
"should not be shown". If this annunciator remains ON, it indicates the
starter has not been automatically disengaged during the engine
starting sequence due to a failed speed sensor.

Can also been seen here:
https://www.youtube.com/watch?v=xcCAL7qE27s

**Comment by magraina** [comment]
Ignition could be set to ON even if the engine is runing but I don't think it will get on with the starter switch as long as the starter- generator is in generator mode and not in starter mode.

**Comment by NewoPL** [comment]
as for the generator off message. I know that it does not show up during engine start. I am just not so sure what prevents it from triggering. I will let go it is not that critical.
as for ignition it definetly go with the starter. I cited you POH above. It is also seen at the movie. It goes off only when the guy switches the starter off.

**Comment by magraina** [comment]
Yes but the Starter on annunciation goes off earlier which means the starter-generator has been automatically switched to generator mode.
It should remain on, if automatically switching fails.

**Comment by magraina** [comment]
So if there is a automatic function why should the starter switch prevent this from happening? It wouldn't be automatically if so.
It can either automatically or manually but it can not be both.

**Comment by NewoPL** [comment]
regarding the ingition operation. Here is what i found in Grand Caravan training manual:
image
Following that I am thinking about implementing engine flameout for some conditions that could be prevented by switching the ingtintion switch to on postions.

**Comment by NewoPL** [comment]
Anyway i think i finally got it right with the latest patch. I will look at the hoycomb problem that you mentioned. However I can see that stnandard events in MSFS do not allow for motor starter position binding. Magraina what do you use to bind it to your 
controller ?

**Comment by magraina** [comment]
I cannot look on my configuration at the moment. But as soon as I can I will tell you!

**Comment by magraina** [comment]
I'm sorry, I'm actually really busy. I hope you don't mind.
I hope I can have a look on your work on the weekend

**Comment by NewoPL** [comment]
no worries. Those changes will require Alpha or Beta release to tested by community. SU8 is comming up soon so some compatibility tweaks may be required as well

**Comment by magraina** [comment]
Yes it's maybe better to first make it su8 compatible if there are issues.
And also then make a alpha release cause it's a lot of stuff and the chance is hight for some bugs ore improvements.

**Comment by magraina** [comment]
Oh, awesome!

**Comment by NewoPL** [comment]
i did merge with the latest model. I  didn't merge 208B_GRAND_CARAVAN_EX_INTERIOR_LOD04.gltf. Do you know what changes suppose to be there ? On the surface it works

**Review by magraina — APPROVED** [review]

**Comment by magraina** [comment]
@NewoPL You ask
> Anyway i think i finally got it right with the latest patch. I will look at the hoycomb problem that you mentioned. However I can see that stnandard events in MSFS do not allow for motor starter position binding. Magraina what do you use to bind it to your controller ?

I use this events in SPAD.next (I don't now actually if there are key bindings available, but I don't think so)
image


image

**Comment by magraina** [comment]
> i did merge with the latest model. I didn't merge 208B_GRAND_CARAVAN_EX_INTERIOR_LOD04.gltf. Do you know what changes suppose to be there ? On the surface it works

I will check them. I think it has something to do with the standby instruments, which was from C172 and not from C208 (I created two dds files for)

**Comment by NewoPL** [comment]
ok i can take a look at starter1_held event - In fact i was not testing this one.

**Comment by magraina** [comment]
@NewoPL  > i did merge with the latest model. I didn't merge 208B_GRAND_CARAVAN_EX_INTERIOR_LOD04.gltf. Do you know what changes suppose to be there ? On the surface it works

I checked the files. They fixed the issue with the Standby Airspeed Indicator!
So the changes with the Standby Alternator LED seems to be the only thing in this files.

**Comment by magraina** [comment]
@NewoPL I will do testing until tomorrow. Hopefully if there are not much problems , I can release this tomorrow

**Pull request merged**
